#!/bin/csh

# ---------------------------
# Fetcher for: RoboDIMM data.
# ---------------------------

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/archive_xfer_setup
 
cd $ARCHIVE_HOME

set KS = certs/pca.private
set KP = geronimo
set TS = certs/itr.public

set HOST = 192.168.4.1
set PORT = 6666

set POLL = 180

#set DEBUG = -Djavax.net.debug=all
set DEBUG
set EGD = -Djava.security.egd=file:/dev/urandom
set APP = ngat.net.SSLFileTransfer

while (1)

    java -Dcpdelim=@ $DEBUG $EGD $APP @id RDIMM_STATUS_GRAB @client @auth @band 5 \
	@key $KS @pass $KP @trust $TS @host $HOST @port $PORT \
	@get /home/eng/proxy/data/robodimm.data @local /occ/data/robodimm.data >>&! /occ/tmp/rdimm.log

    echo "fetch_roboDIMM status: $status"

    #if ($status == 0) then
	cat /occ/data/robodimm.data
    #else
	#echo "Error grabbing RoboDIMM data from ltproxy"
    #endif

    sleep $POLL

end
