#!/bin/csh

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/oss_setup
 
set HOST = localhost
set PORT = 7940
set POLL = 600000
set FILE = /occ/data/oss.data

#java ngat.oss.test.NetworkTest --host $HOST --port $PORT --interval $POLL --results $FILE >>&! /occ/tmp/get_oss.log

java ngat.oss.test.NetworkTest --host $HOST --port $PORT --interval $POLL --results $FILE 

