#!/bin/csh

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/archive_xfer_setup
 
cd $ARCHIVE_HOME

set KS = certs/pca.private
set KP = geronimo
set TS = certs/itr.public

set HOST = 192.168.4.1
set PORT = 6667

set POLL = 60

#set DEBUG = -Djavax.net.debug=all
set DEBUG
set EGD = -Djava.security.egd=file:/dev/urandom
set APP = ngat.net.SSLFileTransfer

while (1)

    java -Dcpdelim=@ $DEBUG $EGD $APP @id ANU_STATUS_GRAB @client @auth @band 5 \
	@key $KS @pass $KP @trust $TS @host $HOST @port $PORT \
	@get /home/eng/murkydata @local /home/occ/anutestdata >>&! /occ/tmp/anu.log

    echo "getanu status: $status"

    #if ($status == 0) then
	cat /home/occ/anutestdata
    #else
	#echo "Error grabbing ANU data from murky"
    #endif

    sleep $POLL

end
