package ngat.rcs.newstatemodel;
import java.io.Serializable;

/**
 * 
 */

/**
 * BAse class for actions generated by a StateModel. Interested handlers should
 * register with the StateModel.
 * 
 * @author snf
 * 
 */
public class ControlAction implements Serializable {

	public static final int CLOSE_ACTION = 1;

	public static final int OPEN_ACTION = 2;

	public static final int STARTUP_ACTION = 3;

	public static final int SHUTDOWN_ACTION = 4;

	public static final int OPERATIONAL_ACTION = 5;

	public static final int ABORT_OPERATIONS_ACTION = 6;

	public static final int INITIALIZE_ACTION = 7;

	public static final int FINALIZE_ACTION = 8;

    public static final int ABORT_OPEN_ACTION  = 11;
    public static final int ABORT_CLOSE_ACTION = 12;
    public static final int ABORT_START_ACTION = 13;
    public static final int ABORT_STOP_ACTION  = 14;

    public static final int FAST_ABORT_OPERATIONS_ACTION = 15;
    public static final int POWERDOWN_ACTION = 16;

	/** The type of action. */
	private int type;

	/**
	 * Create a ControlAction with supplied type.
	 * 
	 * @param type
	 *            The type of action
	 */
	public ControlAction(int type) {
		// TODO Auto-generated constructor stub
		this.type = type;
	}

	/**
	 * @return Returns the type.
	 */
	public int getType() {
		return type;
	}

	/**
	 * A string describing the specified action.type.
	 * @param type The type of action.
	 * @return A string describing the specified action.type.
	 */
	public static String typeToString(int type) {
		switch (type) {
		case CLOSE_ACTION:
			return "CLOSE_ACTION";
		case OPEN_ACTION:
			return "OPEN_ACTION";
		case STARTUP_ACTION:
			return "STARTUP_ACTION";
		case SHUTDOWN_ACTION:
			return "SHUTDOWN_ACTION";
		case OPERATIONAL_ACTION:
			return "OPERATIONAL_ACTION";
		case ABORT_OPERATIONS_ACTION:
			return "ABORT_OPERATIONS_ACTION";
		case INITIALIZE_ACTION:
			return "INITIALIZE_ACTION";
		case FINALIZE_ACTION:
			return "FINALIZE_ACTION";
		case FAST_ABORT_OPERATIONS_ACTION:
		    return "FAST_ABORT_ACTION";
		case POWERDOWN_ACTION:
		    return "RCS_SHUTDOWN_ACTION";
		default:
			return "UNKNOWN";
		}
	}
	
	/**
	 * @return A string describing this action.
	 */
	@Override
	public String toString() {
			return "ControlAction Type="+typeToString(type);
	}
	
}
