/**
 * 
 */
package ngat.rcs.tms.events;

import java.io.Serializable;

import ngat.net.telemetry.StatusCategory;
import ngat.rcs.tms.TaskDescriptor;

/** Base class for events generated by a task during its lifecycle.
 * @author eng
 *
 */
public class TaskLifecycleEvent implements Serializable, StatusCategory {

	private long eventTimeStamp;
	
	/** The task to which this event relates.*/
	protected TaskDescriptor task;
	
	/**
	 * @param task
	 */
	public TaskLifecycleEvent(long eventTimeStamp, TaskDescriptor task) {
		this.eventTimeStamp = eventTimeStamp;
		this.task = task;
	}
	
	

	/**
	 * @return the task
	 */
	public TaskDescriptor getTask() {
		return task;
	}
	
	public long getEventTimeStamp() {
		return eventTimeStamp;
	}
	
	@Override
	public String toString(){ 
		return String.format("TaskEvent [%8d] %tF %tT.%tL %20s %20s", 
				task.getUid(),
				eventTimeStamp, 
				eventTimeStamp,
				eventTimeStamp,
				task.getName(), 
				task.getTypeName());
	}



	public String getCategoryName() {
		return "TLE"; // change for each event type
	}



	public long getStatusTimeStamp() {
		return eventTimeStamp;
	}
}
