#!/bin/csh

# --------------------
# WSF Creation Script.
# --------------------

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/rcx_setup

if ($#argv < 1) then
    echo "Usage: create_wsf <file>"	
    exit 1
endif

# First time it will be file_0.wsf

set wsf = ${1}_0.wsf

if (-e $wsf) then
    printf "%bA Planetarium WSF already exists\n"
    printf "%b  do you want to overwrite (y/n) ?\a"
    set a = "$<"
    if ($a == "y") then
	rm $wsf
    else
	exit 0
    endif
endif
	
touch $wsf

printf "%b#\n# Planetarium Window Schedule File.\n#\n" >> $wsf
printf "%b#\n# INITIAL FILE:\n#\n" >> $wsf

ln -s $wsf windows
