#!/bin/csh

# should have sourced /occ/etc/cshrc

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/rcx_setup

# Usage: wsf_show

set WSFILE = /occ/rcs/planetarium/schedule

java ngat.rcs.gui.WSFEditor  @sched $WSFILE @action show

 
