#!/bin/csh

# should have sourced /occ/etc/cshrc

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/rcx_setup

# Usage: wsf_add <mca> <info> <yyyy-MM-dd#HHmm> <yyyy-MM-dd#HHmm>

if (${#argv} < 4 ) then
    echo "Usage:  wsf_add <mca> <info> <yyyy-MM-dd#HHmm> <yyyy-MM-dd#HHmm>"
    exit 1
endif

set WSFILE = ${RCS_HOME}/planetarium/schedule

cd ${RCS_HOME}

java ngat.rcs.gui.WSFEditor @sched $WSFILE @action add @mca $1 @info $2 @from $3 @to $4

if ($status == 0 ) then
    echo "Window added"
else
    echo "Unable to add window"
endif
