#!/bin/csh

# should have sourced /occ/etc/cshrc

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/rcx_setup

# Usage: wsf_advance

set WSFILE =  ${RCS_HOME}/planetarium/schedule

cd ${RCS_HOME}

java ngat.rcs.gui.WSFEditor @sched $WSFILE @action advance

if ($status == 0 ) then
    echo "Advanced to version: $version "
else
    echo "Unable to advance"
endif
